name: studioflow
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  
  # Banco de dados SQLite
  drift: ^2.18.0
  drift_flutter: ^0.2.0
  
  # Injeção de dependência
  get_it: ^7.7.0
  
  # Gerenciamento de estado
  provider: ^6.1.2
  
  # Ícones
  flutter_svg: ^2.0.10+1
  fl_chart: ^1.2.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Gerador de código do Drift
  drift_dev: ^2.18.0
  build_runner: ^2.4.11
  
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: false
  ios: false
  windows:
    generate: true
    image_path: "assets/logo_icone.png"
    icon_size: 48
  image_path: "assets/logo_icone.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
